export default {
    "SET_CURRENT_VIDEO": "SET_CURRENT_VIDEO",
    "UPDATE_PLAYLIST": "UPDATE_PLAYLIST",
    "TOGGLE_PLAYLIST_EXISTENCE": "TOGGLE_PLAYLIST_EXISTENCE",
    "SET_MOVE_INFO_UP": "SET_MOVE_INFO_UP",
}